version: '3'

services:
  myflix-client:
    build:
      context: ../myflix-client
    environment:
      - REACT_APP_USER_API=http://myflix-userauth:5000
      - REACT_APP_VIDEO_API=http://myflix-videocatalog:5001
      - REACT_APP_RECOMMENDATION_API=http://myflix-recommendation:5002  # New environment variable
    ports:
      - "3000:3000"

  myflix-userauth:
    build:
      context: ../myflix-userauth
    environment:
      - MONGO_URI=mongodb://myflix-mongo:27017/userauth
    depends_on:
      - myflix-mongo
    ports:
      - "5000:5000"

  myflix-mongo:
    image: mongo
    ports:
      - "7000:27017"

  myflix-videocatalog:
    build:
      context: ../myflix-videocatalog
    environment:
      - MONGO_URI=mongodb://myflix-mongo:27017/videocatalog
    ports:
      - "5001:5001"

  myflix-recommendation:
    build:
      context: ../myflix-rec-engine
    environment:
      - MONGO_HOST=myflix-mongo
      - MONGO_PORT=27017
      - MONGO_DB=videocatalog
      # Add other environment variables as needed
    ports:
      - "5002:5002"
