version: '3'

services:
  myflix-client:
    build:
      context: ../myflix-client
    environment:
      - REACT_APP_USER_API=http://localhost:5000
      - REACT_APP_VIDEO_API=http://localhost:5001
    ports:
      - "3000:3000"

  myflix-userauth:
    build:
      context: ../myflix-userauth
    environment:
      - MONGO_URI=mongodb://myflix-mongo:27017/userauth  # Use service name
    depends_on:
      - myflix-mongo  # Ensure MongoDB is started first
    ports:
      - 5000:5000

  myflix-mongo:
    image: mongo
    ports:
      - "7000:27017"

  myflix-videocatalog:
    build:
      context: ../myflix-videocatalog
    environment:
      - MONGO_URI=mongodb://myflix-mongo:27017/videocatalog
    ports:
      - "5001:5001"