version: '3'

services:
  myflix-client:
    image: euandocking/myflix-client:latest
    env_file:
      - .clientEnv
    ports:
      - "3000:3000"

  myflix-userauth:
    image: euandocking/myflix-userauth:latest
    environment:
      - MONGO_URI=mongodb://myflix-mongo:27017/userauth
    depends_on:
      - myflix-mongo
    ports:
      - "5000:5000"

  myflix-mongo:
    image: mongo
    ports:
      - "7000:27017"

  myflix-videocatalog:
    image: euandocking/myflix-videocatalog:latest
    environment:
      - MONGO_URI=mongodb://myflix-mongo:27017/videocatalog
    ports:
      - "5001:5001"

  myflix-recommendation:
    image: euandocking/myflix-rec-engine:latest
    environment:
      - MONGO_HOST=myflix-mongo
      - MONGO_PORT=27017
      - MONGO_DB=videocatalog
    ports:
      - "5002:5002"
