version: '3'

services:
  myflix-client:
    build:
      context: ../myflix-client
      dockerfile: Dockerfile
    env_file:
      - .clientEnv
    ports:
      - "80:3000"

  myflix-userauth:
    build:
      context: ../myflix-userauth
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://myflix-mongo:27017/userauth
    depends_on:
      - myflix-mongo
    ports:
      - "5000:5000"

  myflix-mongo:
    image: mongo
    ports:
      - "7000:27017"

  myflix-videocatalog:
    build:
      context: ../myflix-videocatalog
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://myflix-mongo:27017/videocatalog
    ports:
      - "5001:5001"

  myflix-recommendation:
    build:
      context: ../myflix-rec-engine
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=myflix-mongo
      - MONGO_PORT=27017
      - MONGO_DB=videocatalog
    ports:
      - "5002:5002"
